### ISSUE TITLE
URL Validation

### ISSUE THREAD

**Issue by 8sd** [fistons/TinyTinyFeed#29]
My tt-rss server's domain is `example.pub`. The URL validator says this is an invalid URL.
If I substitute `.pub` with eg `.de` the error doesn't happen.

**Comment by fistons** [comment]
Do you use the version hosted by f-droid repos?

**Comment by 8sd** [comment]
yes

**Comment by fistons** [comment]
Ok, I already fix this bug but it did not make it to the fdroid build. I will try to force a new build.

I keep you posted!

**Comment by 8sd** [comment]
I installed V1.12 today.
It's not working there.

**Comment by 8sd** [comment]
Works, thanks
